package istorage

import "fmt"

//NotFoundError is the error generated by an IStorage when the requested item is not found in the storage
type NotFoundError struct {
	//Type represents which model was in use in the operation
	Type string
	//Field represents which field was used to perform the search
	Field string
	//Key represents the value of the Field
	Key string
}

func (err *NotFoundError) Error() string {
	return fmt.Sprintf("No %s was found where the %s equals %s", err.Type, err.Field, err.Key)
}

//AlreadyExistsError is the error generated by an IStorage when the value intended to be set to an unique field of a element was already used by another element
type AlreadyExistsError struct {
	//Type represents which model was in use in the operation
	Type string
	//Field represents which field was the one where the conflict was found
	Field string
}

func (err *AlreadyExistsError) Error() string {
	return fmt.Sprintf("There is already a/an %s with the same %s", err.Type, err.Field)
}
